### ISSUE TITLE
Use llvm-lit for test cases

### ISSUE THREAD

**Issue by dvc94ch** [monostable/electro-grammar#5]
If our grammar is language agnostic so should the test cases

**Comment by dvc94ch** [comment]
lit is written in python and available on pip. To reproduce the llvm testing experience we also need filecheck [2] which is written in C++. I'm not sure if it is worth the effort or if it is used outside of llvm.
Other solutions to the problem I found are [0] (written in Haskell) [1]. Any thoughts on the issue? I'll port the tests to js for now, otherwise I won't get anything done today =P

- [0] https://github.com/SamirTalwar/Smoke
- [1] https://en.wikipedia.org/wiki/Test_Anything_Protocol
- [2] https://github.com/llvm-mirror/llvm/blob/4604874612fa292ab4c49f96aedefdf8be1ff27e/utils/FileCheck/FileCheck.cpp

**Comment by kasbah** [comment]
We should definitely find a way to avoid repeating the test cases everywhere. 

On the replicad Babeljs transform I started using testing tool that let me just write [input and expected output examples as files](https://github.com/monostable/replicad/tree/a7c44e02e75c5e6d2f46ee6af01981b09137f32b/transform/test/fixtures/resistor). The runner is specific to Babeljs but we could follow this pattern and start making a fixtures directory with `input.txt` and `expected.txt` files. The actual test runner in each language could then be quite simple, so maybe we wouldn't need an extra test framework.

Otherwise I am partial to Haskell solutions but a bit wary of managing a Haskell dependency. I'd want to be sure it's worth it. LLVM-lit looks good too but if we need to pull in an extra CPP file and compile it it might not be the right solution (but maybe it compiles easily and it's worth it, not sure yet).

**Comment by kasbah** [comment]
>    package = '0805'
>    'package.width' = 10

Isn't there a better way to do nesting in TOML? https://github.com/toml-lang/toml#array-of-tables

**Comment by dvc94ch** [comment]
this wouldn't be nice:

```toml
[10k +-10%]
['10k +-10%'.result]
type = 'resistor'
tolerance = 10
```

**Comment by kasbah** [comment]
I would suggest aligning with #9 

```toml
[test-suite]
parser = 'strict'
rule = 'all_packages'
describe = 'chip packages'

[[test]]
it = 'parses 0805'

[test.cases]
metric = '0805'
imperial = '2012'

[test.output]
warnings = ["ambigous_size"]
ignored = ''

[test.output.result]
package = '0805'
```

[This repl type thing](https://binarymuse.github.io/toml-node/) is handy for sketching btw.
